#!/usr/bin/env sh

export NVM_DIR="$HOME/.nvm"

if [ -f .nvmrc ] && [ -s "$NVM_DIR/nvm.sh" ];
then
    . "$NVM_DIR/nvm.sh"
    nvm use --silent
fi;

. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --allow-empty
